name:                tapl
version:             0.1.0.0
github:              "shterrett/tapl"
license:             MIT
author:              "Stuart Terrett"
maintainer:          "shterrett@gmail.com"
copyright:           "2020 Stuart Terrett"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shterrett/tapl#readme>

dependencies:
- base >= 4.7 && < 5
- text
- mtl
- transformers

library:
  source-dirs: src
  ghc-options:
    - -Wall

tests:
  tapl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tapl
    - HUnit
